# Site settings
title: "Community-Centered Analysis | Charlottesville Regional Data Resource Hub"
# email: your-email@example.com
description: "A hub for regional data tools and reports that enable data-informed advocacy to support community building and collective action for change."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://virginiaequitycenter.github.io/cville-equity-atlas"
# github_username:  virginiaequitycenter
# Build settings
sass:
  sass_dir: assets/css/_sass
  style: compressed
# theme: minima
# plugins:
#   - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "pages/reports"
    values:
      og_type: "article"
  - scope:
      path: ""
      type: "pages"
    values:
      is_page: true
      og_type: "website"