# Site settings
title: Charlottesville Regional Equity Atlas
# email: your-email@example.com
description: "An Equity Center Initiative in Democratization of Data to provide tools that enable data rich advocacy in support of community
building and collective action for change."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://virginiaequitycenter.github.io/cville-equity-atlas"
twitter_username: EquityCenterUVA
github_username:  virginiaequitycenter
# Build settings
sass:
  sass_dir: assets/css/_sass
  style: compressed
# theme: minima
# plugins:
#   - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "pages/reports"
    values:
      og_type: "article"
  - scope:
      path: ""
      type: "pages"
    values:
      is_page: true
      og_type: "website"